-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgjBdcbGELEizNseYS
Nlbz4B2VkR8J9ZfrVQwUcYPMdbqgCgYIKoZIzj0DAQehRANCAATZKtcgdiNMcSIq
aK7V692NoWDZeFOEaXukjtxktKuZjwGtXdYzdX4H0gk+b87dbVfeR0Kvqn/lGbWB
F9wA8tLB
-----END PRIVATE KEY-----