import {
  convert24HrFormatTo12Hr,
  translate12HrFormatHourToArabic,
  translateDigitsToArabicIfLanguageIsArabic,
} from '../Utilities/DateAndTimeTools';

const arabicOneWeek = 'اسبوع';
const arabicTwoWeeks = 'اسبوعين';
const arabicThreeOrMoreWeeks = 'اسابيع';
const arabicElevenOrMoreWeeks = 'اسبوعًا';

const getArabicWeek = numberOfWeeks => {
  if (numberOfWeeks == 1) return arabicOneWeek;
  if (numberOfWeeks == 2) return arabicTwoWeeks;
  if (numberOfWeeks >= 3 && numberOfWeeks < 11) return arabicThreeOrMoreWeeks;
  return arabicElevenOrMoreWeeks;
}

const UIText = {
  en: {
    login: 'Login',
    signUp: 'SIGN UP',
    fullName: 'Full name',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    user: 'User',
    consultant: 'Consultant',
    keepLoggedIn: 'Keep me logged in',
    forgotPassword: 'Forgot password?',
    dontHaveAccount: `Don't have an account?`,
    haveAccount: 'Already have an account?',
    blankName: 'Name cannot be blank',
    invalidEmail: 'Email is invalid',
    blankEmail: 'Email cannot be blank',
    invalidPassword: 'Password must be at least 8 characters',
    blankPassword: 'Password cannot be blank',
    invalidPasswordConfirmation: 'Passwords do not match',
    blankPasswordConfirmation: 'Password confirmation cannot be blank',
    noUserMessage: 'Email or password is incorrect',
    emailAlreadyExists: 'Email is already in use by another account',
    selectConsultant: 'Select consultation expert',
    call: 'call',
    selectDate: 'Select Date',
    selectTime: 'Select Time',
    scheduleAppointment: 'Schedule Appointment',
    select: 'Select',
    selectConsultantFirst: 'Select a consultant first',
    selectTimeAndDateFirst: 'Select date and time first',
    scheduleAppointment: 'Schedule Appointment',
    myAccount: 'My Account',
    selectAvatar: 'Select Avatar',
    accountDetails: 'Account Details',
    apply: 'Apply',
    discard: 'Discard',
    imageUploaded: 'Image Uploaded Successfully',
    changesApplied: 'Changes Applied Successfully',
    settings: 'Settings',
    confirmLogout: 'Are you sure you want to logout?',
    logout: 'Logout',
    sendResetEmail: 'Send the reset-email to:',
    emailSentSuccessfully: 'The email has been sent successfully',
    someThingWentWrong: 'Some thing went wrong. Please try again',
    send: 'Send',
    noUserCorrespondingToEmail: 'There is no user corresponding to the specified email',
    activationMessage: `Your consultant account will be reviewed and you'll be notified once it's activated`,
    ok: 'Ok',
    loginFirst: 'You must login first',
    status: 'Status',
    requested: 'Requested',
    requestedAdjective: 'requested',
    missed: 'Missed',
    missedAdjective: 'missed',
    accepted: 'Accepted',
    acceptedAdjective: 'upcoming',
    declined: 'Declined',
    declinedAdjective: 'declined',
    completedAdjective: 'completed',
    loginToViewAppointments: 'Login to view your scheduled\nappointments',
    language: 'Language',
    english: 'English',
    arabic: 'Arabic',
    startConsultation: 'Start',
    accept: 'Accept',
    decline: 'Decline',
    appointmentRequest: 'Appointment Request',
    schedule: 'Schedule',
    myAppointments: 'My Appointments',
    preferences: 'Preferences',
    pricePerCall: 'Price per call',
    applyChanges: 'Apply Changes',
    available: 'Available',
    from: 'from',
    to: 'to',
    numberOfWeeksAppointmentMustBeWithin: 'Maximum number of weeks appointment must be within',
    timeWindow: 'Minimum number of minutes before a new appointment can be scheduled',
    consultationPrice: 'Consultation price',
    reEnterPassword: 'Please re-enter you password to change the email address',
    changeEmail: 'Change email address',
    incorrectPassword: 'The password is incorrect',
    requests: 'Requests',
    requestedAppointments: 'Requested Appointments',
    upcoming: 'Upcoming',
    upcomingAppointments: 'Upcoming Appointments',
    completed: 'Completed',
    completedAppointments: 'Completed Appointments',
    pay: 'Pay',
    cancel: 'Cancel',
    paymentCompletedSuccessfully: 'Payment Completed Successfully',
    pending: 'Pending',
    somethingWentWrong: 'Something went wrong. Please try again later',
    appointmentScheduledSuccessfully: 'Appointment scheduled successfully',
    callPriceMustBeNumber: 'Call price must be a number',
    numberOfWeeksAppointmentMustBeWithinMustBeNumber: 'Number of weeks must be a number',
    timeWindowMustBeNumber: 'Number of minutes must be a number',
    consultationTimedOut: 'Maximum number of minutes per consultation has been reached',
    submit: 'Submit',
    consultationCompleted: 'Your dream consultation is completed',
    bio: 'Bio',
    dashboard: 'Dashboard',
    grantAdministration: 'Grant administration',
    addAdministrator: 'Add Administrator',
    unReviewedConsultants: 'Unreviewed Consultants',
    noNewConsultantsToBeReviewed: 'No New Consultants To Be Reviewed',
    charge: 'Charge',
    amountChargedSuccessfully: 'Amount charged successfully',
    paymentCouldNotBeCompleted: 'Payment could not be completed. Try again later',
    insufficientBalance: `The user's balance is insufficient to complete the payment`,
    addAdministrators: 'Administrators',
    activateConsultants: 'Activate',
    paymentDues: 'Payment Dues',
    paymentDue: 'Payment Due',
    paymentNote: 'Note: Appointment fee will be charged when the consultant accepts the appointment',
    minimumPricePerCallIsHalfDollar: 'Minimum price per call is $0.5',
    paymentCompleted: 'Funded',
    joinCall: 'Join Call',
    help: 'Help',
    contactUs: 'Contact Us',
    iAgreeTo: 'I agree to the',
    termsOfService: 'Terms of Service',
    and: 'and',
    privacyPolicy: 'Privacy Policy',
    selectDateWithin: numberOfWeeks => `Select a date within ${numberOfWeeks} week${numberOfWeeks > 1 ? 's' : ''}`,
    selectHourWithin: (from , to) => `Select time between ${convert24HrFormatTo12Hr(from)} and ${convert24HrFormatTo12Hr(to)}`,
    mustSelectHourWithin: (from , to) => `Time must be between ${convert24HrFormatTo12Hr(from)} and ${convert24HrFormatTo12Hr(to)}`,
    appointmentIsNowNotification: peerName => `Your Dream Consultation With ${peerName} has started. Tab to join the call.`,
    appointmentMessageWhileAnotherCallIsActive: peerName => `Your Dream Consultation With ${peerName} has started. Start the consultation from your appointments screen to join the call`,
    missedConsultationNotification: peerName => `You missed your Consultation appointment With ${peerName}`,
    waitForPeerToJoinChannel: peerName => `Wait for ${peerName} to join the channel`,
    joinCallWith: peerName => `Join call with ${peerName} to start the consultation`,
    userJoinedChannel: peerName => `${peerName} Joined the channel`,
    sendingInvitationTo: peerName => ` Sending channel invitation to ${peerName}`,
    platformPercentage: percentage => `Platform's Percentage is ${percentage}%`,
    noAppointments: (status='') => `There aren't any ${status.toLowerCase()} appointments`,
    peerNotConnected: peerName => `${peerName} Is Not connected`,
    chargeConsultationPrice: price => `Accept appointment and charge $${price}`,
    checkInternetConnectionAndTry: (action = 'again') => `Check your internet connection and try ${action}`,
    selectedTimeNotAvailableTry: (nearestTimeBefore, nearestTimeAfter) => {
      nearestTimeBefore = nearestTimeBefore || '';
      nearestTimeAfter = nearestTimeAfter || '';
      const includeOr = nearestTimeBefore && nearestTimeAfter;
      const showSuggestions = nearestTimeBefore || nearestTimeAfter;
      const suggestions = `\nYou can select ${nearestTimeBefore}${includeOr ? ' or ' : ''}${nearestTimeAfter}`
      return `Selected time is already taken.${showSuggestions ? suggestions : ''}`
    },
    months: {
      0: 'Jan',
      1: 'Feb',
      2: 'Mar',
      3: 'Apr',
      4: 'May',
      5: 'Jun',
      6: 'Jul',
      7: 'Aug',
      8: 'Sept',
      9: 'Oct',
      10: 'Nov',
      11: 'Dec',
    }
  },
  ar: {
    login: 'تسجيل دخول',
    signUp: 'إنشاء حساب',
    fullName: 'الاسم كاملًا',
    email: 'البريد الإلكترونى',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    user: 'مستخدم',
    consultant: 'مستشار',
    keepLoggedIn: 'ابق تسجيل دخولي',
    forgotPassword: 'نسيت كلمة المرور؟',
    dontHaveAccount: 'ليس لديك حساب؟',
    haveAccount: 'لديك حساب؟',
    blankName: 'الاسم لا يمكن أن يُترك فارغًا',
    invalidEmail: 'البريد الإلكتروني غير صحيح',
    blankEmail: 'البريد الإلكتروني لا يمكن أن يُترك فارغًا',
    invalidPassword: 'كلمة المرور يجب ألا تكون أقل من ٨ رموز',
    blankPassword: 'كلمة المرور لا يمكن أن تُترك فارغة',
    invalidPasswordConfirmation: 'كلمتي المرور غير متوافقين',
    blankPasswordConfirmation: 'تأكيد كلمة المرور لا يمكن أن يُترك فارغًا',
    noUserMessage: 'البريد الإلكتروني أو كلمة المرور غير صحيحين',
    emailAlreadyExists: 'البريد الإلكتروني مُسجل بالفعل لحساب آخر',
    selectConsultant: 'اختر مُفسر للرؤى واحجز موعد',
    call: 'مكالمة',
    selectDate: 'اختر تاريخًا',
    selectTime: 'اختر توقيتًا',
    scheduleAppointment: 'تحديد الموعد',
    select: 'اختيار',
    selectConsultantFirst: 'اختر متسشارًا أولًا',
    selectTimeAndDateFirst: 'اختر تاريخًا و موعدًا أولًا',
    addPaymentMethod: 'إضافة وسيلة دفع',
    myAccount: 'حسابي',
    selectAvatar: 'اختر صورة شخصية',
    accountDetails: 'بيانات الحساب',
    apply: 'تغيير',
    discard: 'إلغاء',
    imageUploaded: 'تم حفظ الصورة بنجاح',
    changesApplied: 'تم حفظ التغييرات بنجاح',
    settings: ' الإعدادات',
    confirmLogout: 'هل أنت متأكد من تسجيل الخروج',
    logout: 'تسجيل الخروج',
    sendResetEmail: 'إرسال البريد الإلكتروني الخاص بإعادة تعيين كلمة السر إلى',
    emailSentSuccessfully: 'تم إرسال البريد الإلكتروني بنجاح',
    someThingWentWrong: 'حدث خطأ ما. اعد المحاولة من فضلك',
    send: 'إرسال',
    noUserCorrespondingToEmail: 'لا يوجد مستخدم مُسجل بهذا البريد الإلكتروني',
    activationMessage: 'سيتم مراجعة حسابك وإخطارك فور تفعيله',
    ok: `حسنًا`,
    loginFirst: 'يجب عليك تسجيل الدخول أولًا',
    status: 'الحالة',
    requested: 'تم الطلب',
    requestedAdjective: 'مطلوبة',
    missed: ' فاتت',
    missedAdjective: 'فائتة',
    accepted: 'تم القبول',
    acceptedAdjective: 'قادمة',
    declined: 'تم الرفض',
    declinedAdjective: 'تم رفضها',
    completedAdjective: 'تم الإنتهاء منها',
    loginToViewAppointments: 'قم بتسجيل الدخول لرؤية مواعيدك\nالمسجلة',
    language: 'اللغة',
    english: 'الإنجليزية',
    arabic: 'العربية',
    startConsultation: 'ابدأ',
    accept: 'قبول',
    decline: 'رفض',
    appointmentRequest: 'طلب تحديد موعد',
    schedule: 'تحديد موعد',
    myAppointments: 'مواعيدي',
    preferences: 'خيارات العمل',
    pricePerCall: 'سعر المكالمة',
    applyChanges: 'حفظ التغييرات',
    available: 'متوفر',
    from: 'من',
    to: 'إلى',
    numberOfWeeksAppointmentMustBeWithin: 'أقصى عدد أسابيع يمكن تحديد الموعد خلاله',
    timeWindow: 'أقل عدد دقائق قبل السماح بتسجيل موعد جديد',
    consultationPrice: 'سعر الاستشارة',
    scheduleAppointment: 'سجل موعد',
    reEnterPassword: 'برجاء إعادة إدخال كلمة المرور لتغيير البريد الإلكتروني',
    changeEmail: 'تغيير البريد الإلكتروني',
    incorrectPassword: 'كلمة المرور غير صحيحة',
    requests: 'المطلوبة',
    requestedAppointments: 'المواعيد المطلوبة',
    upcoming: 'القادمة',
    upcomingAppointments: 'المواعيد القادمة',
    completed: 'المنتهية',
    completedAppointments: 'المواعيد المنتهية',
    pay: 'الدفع',
    cancel: 'إلغاء',
    paymentCompletedSuccessfully: 'تم إتمام عملية الدفع بنجاح',
    pending: 'طلبات في إنتظار التأكيد',
    somethingWentWrong: 'هناك خطأ ما. برجاء المحاولة في وقتٍ لاحق',
    appointmentScheduledSuccessfully: 'تم تسجيل الموعد بنجاح',
    callPriceMustBeNumber: 'سعر المكالمة يجب أن يكون رقمًا',
    numberOfWeeksAppointmentMustBeWithinMustBeNumber: 'عدد الأسابيع يجب أن يكون رقمًا',
    timeWindowMustBeNumber: 'عدد الدقائق يجب أن يكون رقمًا',
    consultationTimedOut: 'تم الوصول للحد الأقصى من الدقائق في المكالمة',
    submit: 'تقييم',
    consultationCompleted: 'تم الإنتهاء من الاستشارة',
    bio: 'النبذة التعريفية',
    dashboard: 'وحدة التحكم',
    grantAdministration: 'اعط حق الإدارة',
    addAdministrator: 'اضف مستشار',
    unReviewedConsultants: 'المستشارين الذين لم يتم تفعيلهم',
    noNewConsultantsToBeReviewed: 'لا يوجد مستشارين جدد ليتم تفعيلهم',
    charge: 'حاسب',
    amountChargedSuccessfully: 'تمت عملية محاسبة المستخدم بنجاح',
    paymentCouldNotBeCompleted: 'لم تتم عملية محاسبة المستخدم بنجاح. برجاء المحاولة في وقتٍ لاحق',
    insufficientBalance: 'رصيد المستخدم غير كافي لإتمام عملية الدفع',
    addAdministrators: 'مديرون',
    activateConsultants: 'تفعيل',
    paymentDues: 'مستحقات الدفع',
    paymentDue: 'مستحقات الدفع',
    paymentNote: 'ملحوظة: سيتم خصم تكلفة الموعد عند قبول المستشار',
    minimumPricePerCallIsHalfDollar: 'أقل سعر للمكالمة يمكن اختياره هو $0.5',
    paymentCompleted: 'تم الدفع',
    joinCall: 'الإنضمام إلى المكالمة',
    help: 'المساعدة',
    contactUs: 'الاتصال بنا',
    iAgreeTo: 'أنا أوافق على',
    termsOfService: 'شروط الاستخدام',
    and: 'و',
    privacyPolicy: 'سياسة الخصوصية',
    noAppointments: (status='') => `لا يوجد أي مواعيد ${status.toLowerCase()}`,
    selectDateWithin: numberOfWeeks => translateDigitsToArabicIfLanguageIsArabic(`اختر موعدًا في خلال${numberOfWeeks > 2 ? ` ${numberOfWeeks}` : ''} ${getArabicWeek(numberOfWeeks)}`),
    selectHourWithin: (from , to) => translate12HrFormatHourToArabic(`اختر موعدًا بين الساعة ${convert24HrFormatTo12Hr(from)} و ${convert24HrFormatTo12Hr(to)}`),
    mustSelectHourWithin: (from , to) => translate12HrFormatHourToArabic(`يجب أن يكون الموعد بين الساعة ${convert24HrFormatTo12Hr(from)} و ${convert24HrFormatTo12Hr(to)}`),
    appointmentIsNowNotification: peerName => `استشارتك مع ${peerName} قد بدأت. اضغط لتبدأ المكالمة`,
    appointmentMessageWhileAnotherCallIsActive: peerName => `استشارتك مع ${peerName} قد بدأت. قم ببدأ الاستشارة من شاشة المواعيد لتبدأ المكالمة`,
    missedConsultationNotification: peerName => `لقد فاتك موعد الإستشارة مع ${peerName}`,
    waitForPeerToJoinChannel: peerName => `انتظر ${peerName} لينضم إلى القناة`,
    joinCallWith: peerName => `انضم للمكالمة مع ${peerName} لتبدأ الاستشارة`,
    userJoinedChannel: peerName => `${peerName} قد إنضم للقناة`,
    selectedTimeNotAvailableTry: (nearestTimeBefore, nearestTimeAfter) => `الموعد الذي تم اختياره محجوز بالفعل\nيمكنك اختيار ${nearestTimeBefore} أو ${nearestTimeAfter}`,
    sendingInvitationTo: peerName => ` جاري إرسال دعوة للإنضمام إلى ${peerName}`,
    platformPercentage: percentage => translateDigitsToArabicIfLanguageIsArabic( `نسبة البرنامج ${percentage}٪`),
    peerNotConnected: peerName => `${peerName} ليس متصلًا`,
    chargeConsultationPrice: price => `قبول الموعد و محسابة المستخدم على $${price}`,
    checkInternetConnectionAndTry: action => `قم بالتأكد من اتصالك بالإنترنت ثم حاول ${action || 'مجددًا'}`,
    selectedTimeNotAvailableTry: (nearestTimeBefore, nearestTimeAfter) => {
      nearestTimeBefore = nearestTimeBefore || '';
      nearestTimeAfter = nearestTimeAfter || '';
      const includeOr = nearestTimeBefore && nearestTimeAfter;
      const showSuggestions = nearestTimeBefore || nearestTimeAfter;
      const suggestions = `\nيمكنك اختيار ${nearestTimeBefore}${includeOr ? ' أو ' : ''}${nearestTimeAfter}`
      return `.الموعد الذي تم اختياره محجوز بالفعل${showSuggestions ? suggestions : ''}`
    },
    months: {
      0: 'يناير',
      1: 'فبراير',
      2: 'مارس',
      3: 'أبريل',
      4: 'مايو',
      5: 'يونيو',
      6: 'يوليو',
      7: 'أغسطس',
      8: 'سبتمبر',
      9: 'أكتوبر',
      10: 'نوفمبر',
      11: 'ديسمبر',
    }
  },
  englishToArabicDigitsMap: {0: '٠', 1: '١', 2: '٢', 3: '٣', 4: '٤', 5: '٥', 6: '٦', 7: '٧', 8: '٨', 9: '٩'},
  englishToArabicTimePeriodsMap: {am: 'ص', pm: 'م'},
}

export default UIText;